### Read all users
GET http://localhost:3001/api/v1/users

### Create a new user
POST http://localhost:3001/api/v1/users
Content-Type: application/json

{
  "username": "Charlie",
  "email": "charlie@example.com",
  "password": "pass123456"
}

### Update a user
PUT http://localhost:3001/api/v1/users/4
Content-Type: application/json

{
  "username": "Stephen",
  "email": "stephen@example.com",
  "password": "pass1234567"
}

### Delete a user
DELETE http://localhost:3001/api/v1/users/4